services:
  way-finding-coaching:
    image: ghcr.io/m6o4solutions/way-finding-coaching-project:latest
    container_name: way-finding-coaching
    restart: unless-stopped
    networks:
      - traefik-network
    env_file:
      - stack.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.way-finding-coaching.rule=Host(`way-finding.co.ke`) || Host(`www.way-finding.co.ke`)"
      - "traefik.http.routers.way-finding-coaching.entrypoints=websecure"
      - "traefik.http.routers.way-finding-coaching.tls.certresolver=letsencrypt"
      - "traefik.http.services.way-finding-coaching.loadbalancer.server.port=3000"

networks:
  traefik-network:
    external: true
    name: traefik-network
