name: Cleanup Old Docker Image from GHCR

on:
  schedule:
    - cron: "0 2 * * 0"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Derive Image Name
        id: image
        run: |
          echo "name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT

      - name: Delete Old Docker Images
        uses: snok/container-retention-policy@v2.2.1
        with:
          image-names: ${{ steps.image.outputs.name }}
          cut-off: One minute ago UTC
          keep-at-least: 2
          account-type: personal
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
